notifications:
  email:
  - apple.builds@sagebase.org
language: objective-c
osx_image: xcode10.2
xcode_workspace: mPower2.xcworkspace
xcode_scheme: mPower2
cache:
- bundler
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
install:
- pip install travis-wait-improved
- gem install bundler
- bundle install
script:
- travis-wait-improved --timeout 30 ./travis/build.sh
branches:
  only:
  - master
  - "/^stable-.*$/"
